sudo: required

language: go

services:
    - docker version
    - docker-compose version

before_install:
    
   - ls -ralt

script:
    - docker-compose up -d
    - curl "127.0.0.1:8080/transfers"
